FROM node:18-alpine

# Build-time arguments for runtime configuration
ARG DB_HOST
ARG DB_PORT
ARG DB_DATABASE
ARG DB_USERNAME
ARG DB_PASSWORD
ARG ATLANTIS_DB_HOST
ARG ATLANTIS_DB_PORT
ARG ATLANTIS_DB_DATABASE
ARG ATLANTIS_DB_USERNAME
ARG ATLANTIS_DB_PASSWORD
ARG SERVER_IP
ARG TIME_ZONE

# Set environment variables (can be overridden at runtime)
ENV DB_HOST=$DB_HOST \
    DB_PORT=$DB_PORT \
    DB_DATABASE=$DB_DATABASE \
    DB_USERNAME=$DB_USERNAME \
    DB_PASSWORD=$DB_PASSWORD \
    ATLANTIS_DB_HOST=$ATLANTIS_DB_HOST \
    ATLANTIS_DB_PORT=$ATLANTIS_DB_PORT \
    ATLANTIS_DB_DATABASE=$ATLANTIS_DB_DATABASE \
    ATLANTIS_DB_USERNAME=$ATLANTIS_DB_USERNAME \
    ATLANTIS_DB_PASSWORD=$ATLANTIS_DB_PASSWORD \
    SERVER_IP=$SERVER_IP \
    TIME_ZONE=$TIME_ZONE

# Install app dependencies
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci

# Copy source and build
COPY . .
RUN npm run build

# Expose the port used in src/main.ts
EXPOSE 4000

CMD ["node", "dist/main.js"]


#
#